// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stocks.proto

package org.developerworks.stocks;

public final class Stocks {
  private Stocks() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Quote extends
      com.google.protobuf.GeneratedMessage {
    // Use Quote.newBuilder() to construct.
    private Quote() {
      initFields();
    }
    private Quote(boolean noInit) {}
    
    private static final Quote defaultInstance;
    public static Quote getDefaultInstance() {
      return defaultInstance;
    }
    
    public Quote getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.developerworks.stocks.Stocks.internal_static_stocks_Quote_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.developerworks.stocks.Stocks.internal_static_stocks_Quote_fieldAccessorTable;
    }
    
    // required string symbol = 1;
    public static final int SYMBOL_FIELD_NUMBER = 1;
    private boolean hasSymbol;
    private java.lang.String symbol_ = "";
    public boolean hasSymbol() { return hasSymbol; }
    public java.lang.String getSymbol() { return symbol_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required double price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private boolean hasPrice;
    private double price_ = 0D;
    public boolean hasPrice() { return hasPrice; }
    public double getPrice() { return price_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasSymbol) return false;
      if (!hasName) return false;
      if (!hasPrice) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSymbol()) {
        output.writeString(1, getSymbol());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasPrice()) {
        output.writeDouble(3, getPrice());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSymbol()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSymbol());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getPrice());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.developerworks.stocks.Stocks.Quote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Quote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.developerworks.stocks.Stocks.Quote prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.developerworks.stocks.Stocks.Quote result;
      
      // Construct using org.developerworks.stocks.Stocks.Quote.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.developerworks.stocks.Stocks.Quote();
        return builder;
      }
      
      protected org.developerworks.stocks.Stocks.Quote internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.developerworks.stocks.Stocks.Quote();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.developerworks.stocks.Stocks.Quote.getDescriptor();
      }
      
      public org.developerworks.stocks.Stocks.Quote getDefaultInstanceForType() {
        return org.developerworks.stocks.Stocks.Quote.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.developerworks.stocks.Stocks.Quote build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.developerworks.stocks.Stocks.Quote buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.developerworks.stocks.Stocks.Quote buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        org.developerworks.stocks.Stocks.Quote returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.developerworks.stocks.Stocks.Quote) {
          return mergeFrom((org.developerworks.stocks.Stocks.Quote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.developerworks.stocks.Stocks.Quote other) {
        if (other == org.developerworks.stocks.Stocks.Quote.getDefaultInstance()) return this;
        if (other.hasSymbol()) {
          setSymbol(other.getSymbol());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSymbol(input.readString());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 25: {
              setPrice(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required string symbol = 1;
      public boolean hasSymbol() {
        return result.hasSymbol();
      }
      public java.lang.String getSymbol() {
        return result.getSymbol();
      }
      public Builder setSymbol(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSymbol = true;
        result.symbol_ = value;
        return this;
      }
      public Builder clearSymbol() {
        result.hasSymbol = false;
        result.symbol_ = getDefaultInstance().getSymbol();
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // required double price = 3;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public double getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(double value) {
        result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:stocks.Quote)
    }
    
    static {
      defaultInstance = new Quote(true);
      org.developerworks.stocks.Stocks.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stocks.Quote)
  }
  
  public static final class Portfolio extends
      com.google.protobuf.GeneratedMessage {
    // Use Portfolio.newBuilder() to construct.
    private Portfolio() {
      initFields();
    }
    private Portfolio(boolean noInit) {}
    
    private static final Portfolio defaultInstance;
    public static Portfolio getDefaultInstance() {
      return defaultInstance;
    }
    
    public Portfolio getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.developerworks.stocks.Stocks.internal_static_stocks_Portfolio_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.developerworks.stocks.Stocks.internal_static_stocks_Portfolio_fieldAccessorTable;
    }
    
    // repeated .stocks.Quote quote = 1;
    public static final int QUOTE_FIELD_NUMBER = 1;
    private java.util.List<org.developerworks.stocks.Stocks.Quote> quote_ =
      java.util.Collections.emptyList();
    public java.util.List<org.developerworks.stocks.Stocks.Quote> getQuoteList() {
      return quote_;
    }
    public int getQuoteCount() { return quote_.size(); }
    public org.developerworks.stocks.Stocks.Quote getQuote(int index) {
      return quote_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      for (org.developerworks.stocks.Stocks.Quote element : getQuoteList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (org.developerworks.stocks.Stocks.Quote element : getQuoteList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (org.developerworks.stocks.Stocks.Quote element : getQuoteList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.developerworks.stocks.Stocks.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.developerworks.stocks.Stocks.Portfolio prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.developerworks.stocks.Stocks.Portfolio result;
      
      // Construct using org.developerworks.stocks.Stocks.Portfolio.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.developerworks.stocks.Stocks.Portfolio();
        return builder;
      }
      
      protected org.developerworks.stocks.Stocks.Portfolio internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new org.developerworks.stocks.Stocks.Portfolio();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.developerworks.stocks.Stocks.Portfolio.getDescriptor();
      }
      
      public org.developerworks.stocks.Stocks.Portfolio getDefaultInstanceForType() {
        return org.developerworks.stocks.Stocks.Portfolio.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public org.developerworks.stocks.Stocks.Portfolio build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.developerworks.stocks.Stocks.Portfolio buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.developerworks.stocks.Stocks.Portfolio buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.quote_ != java.util.Collections.EMPTY_LIST) {
          result.quote_ =
            java.util.Collections.unmodifiableList(result.quote_);
        }
        org.developerworks.stocks.Stocks.Portfolio returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.developerworks.stocks.Stocks.Portfolio) {
          return mergeFrom((org.developerworks.stocks.Stocks.Portfolio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.developerworks.stocks.Stocks.Portfolio other) {
        if (other == org.developerworks.stocks.Stocks.Portfolio.getDefaultInstance()) return this;
        if (!other.quote_.isEmpty()) {
          if (result.quote_.isEmpty()) {
            result.quote_ = new java.util.ArrayList<org.developerworks.stocks.Stocks.Quote>();
          }
          result.quote_.addAll(other.quote_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              org.developerworks.stocks.Stocks.Quote.Builder subBuilder = org.developerworks.stocks.Stocks.Quote.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addQuote(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .stocks.Quote quote = 1;
      public java.util.List<org.developerworks.stocks.Stocks.Quote> getQuoteList() {
        return java.util.Collections.unmodifiableList(result.quote_);
      }
      public int getQuoteCount() {
        return result.getQuoteCount();
      }
      public org.developerworks.stocks.Stocks.Quote getQuote(int index) {
        return result.getQuote(index);
      }
      public Builder setQuote(int index, org.developerworks.stocks.Stocks.Quote value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.quote_.set(index, value);
        return this;
      }
      public Builder setQuote(int index, org.developerworks.stocks.Stocks.Quote.Builder builderForValue) {
        result.quote_.set(index, builderForValue.build());
        return this;
      }
      public Builder addQuote(org.developerworks.stocks.Stocks.Quote value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.quote_.isEmpty()) {
          result.quote_ = new java.util.ArrayList<org.developerworks.stocks.Stocks.Quote>();
        }
        result.quote_.add(value);
        return this;
      }
      public Builder addQuote(org.developerworks.stocks.Stocks.Quote.Builder builderForValue) {
        if (result.quote_.isEmpty()) {
          result.quote_ = new java.util.ArrayList<org.developerworks.stocks.Stocks.Quote>();
        }
        result.quote_.add(builderForValue.build());
        return this;
      }
      public Builder addAllQuote(
          java.lang.Iterable<? extends org.developerworks.stocks.Stocks.Quote> values) {
        if (result.quote_.isEmpty()) {
          result.quote_ = new java.util.ArrayList<org.developerworks.stocks.Stocks.Quote>();
        }
        super.addAll(values, result.quote_);
        return this;
      }
      public Builder clearQuote() {
        result.quote_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:stocks.Portfolio)
    }
    
    static {
      defaultInstance = new Portfolio(true);
      org.developerworks.stocks.Stocks.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stocks.Portfolio)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stocks_Quote_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stocks_Quote_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stocks_Portfolio_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stocks_Portfolio_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014stocks.proto\022\006stocks\"4\n\005Quote\022\016\n\006symbo" +
      "l\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\r\n\005price\030\003 \002(\001\")\n\t" +
      "Portfolio\022\034\n\005quote\030\001 \003(\0132\r.stocks.QuoteB" +
      "\033\n\031org.developerworks.stocks"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_stocks_Quote_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_stocks_Quote_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stocks_Quote_descriptor,
              new java.lang.String[] { "Symbol", "Name", "Price", },
              org.developerworks.stocks.Stocks.Quote.class,
              org.developerworks.stocks.Stocks.Quote.Builder.class);
          internal_static_stocks_Portfolio_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_stocks_Portfolio_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stocks_Portfolio_descriptor,
              new java.lang.String[] { "Quote", },
              org.developerworks.stocks.Stocks.Portfolio.class,
              org.developerworks.stocks.Stocks.Portfolio.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
